-- AlterTable
ALTER TABLE `User`
ADD COLUMN `businessName` VARCHAR(191) NULL,
ADD COLUMN `businessType` VARCHAR(191) NULL,
ADD COLUMN `panNumber` VARCHAR(191) NULL,
ADD COLUMN `gstNumber` VARCHAR(191) NULL,
ADD COLUMN `aadhaarLast4` VARCHAR(191) NULL;
